# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B verify --file pom.xml
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.5
      if: always()
      with:
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: target/site/serenity # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy
